# Server sozlamalari
server.port=8080
spring.application.name=jpa-demo

# H2 Database (RAM da ishlaydi - test uchun)
# PostgreSQL ga otish uchun bu qismni ochirib, pastdagi PostgreSQL ni yoqing
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# PostgreSQL (production uchun)
# spring.datasource.url=jdbc:postgresql://localhost:5432/jpademo
# spring.datasource.username=postgres
# spring.datasource.password=123
# spring.datasource.driver-class-name=org.postgresql.Driver

# JPA sozlamalari
spring.jpa.hibernate.ddl-auto=update     # Jadvalni avtomatik yaratish/yangilash
spring.jpa.show-sql=true                 # SQL so'rovlarni konsolga chiqarish
spring.jpa.properties.hibernate.format_sql=true  # SQL ni chiroyli qilib chiqarish
